### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by amandexspeed** [PatchworkMC/patchwork-patcher#103]
I tried to join the discord server but the invitacion was expired.
I'm really excited to use this mod/program when it's launched and It will be really important in the world of minecraft mods.
The link I tried to use: https://discord.com/invite/YYZtNBG

**Comment by ProjectET** [comment]
The server is closed for the time being because there are a lack of contributions and spending the time and effort moderating an effectively dead server is a waste of time. The main dev team of patchwork can be found on the QuiltMC discord here: https://discord.quiltmc.org/community "Patchwork development will resume once Quilt is 'done'." quoted from Glitch. And no, patchwork isn't nearly in any shape usable.

**Comment by amandexspeed** [comment]
Ok, I was hopeful that someday I would be able to use this project and expand the possibilities of using my mods. But I understand the difficulty of trying to unite forge and fabric
