### ISSUE TITLE
[Question] Time Frame for 1.15?

### ISSUE THREAD

**Issue by GamingInfinite** [PatchworkMC/patchwork-patcher#43]
Just something that I'd like to know, when is 1.15 support coming?  I don't mean to be rude.

**Comment by coderbot16** [comment]
In the near future we plan to stick on 1.14 for a few reasons, including the fact that Forge has designated it as an LTS version. Also, [Create](https://www.curseforge.com/minecraft/mc-mods/create), one of the mods that we would like to get running on Patchwork, only supports 1.14 at the moment.

Supporting 1.13/1.15/etc in patcher is pretty trivial, but it is harder to support it in API. I would like a solution in API that would allow parallel support for 1.14 and 1.15 instead of having to maintain two separate code branches at the very least.

Eventually we will support 1.15, but I can't provide any ETA on when it will happen.

**Comment by TheGlitch76** [comment]
We also have a [discord](https://discord.gg/YYZtNBG) where you can follow our development channels to get an idea of when things are happening.

**Comment by GamingInfinite** [comment]
@TheGlitch76 I dunno if that was supposed to allow me to access the discord but the invite expired.  If it's been linked somewhere else then I'll just find it there.  If not, maybe put the invite link in the README.md with no expiration.

**Comment by TheGlitch76** [comment]
Whoops, I pasted it wrong. Should work fine now.

**Comment by coderbot16** [comment]
Update: Forge appears to be committing to supporting 1.14 even with the release of 1.15, meaning that we will need to support 1.14 for the foreseeable future. However, that does not preclude also supporting 1.15 and 1.16 as well while supporting 1.14.

**Comment by TheGlitch76** [comment]
1.16 is here!
